# Basic Numpy 

*The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.* [(link)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

![](resource/numpy.png)

- **Size** - Numpy data structures take up less space
- **Performance** - they have a need for speed and are faster than lists
- **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built in.

Download **Numpy Cheat Sheet** from datacamp [(Download)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

In [1]:
import numpy as np

In [ ]:
np.__version__

### Create 1D Vector

In [ ]:
# vector baris (axis 0)

vector_row = np.array([1,2,3,4,5,6])

print(vector_row)


### Create 2D Vector (Matrix)

In [ ]:
matrix = np.array([[1,2,3,5],
                   [4,5,6,5],
                   [7,8,9,9]])

print(matrix)

### Akses elemen Vector

In [ ]:
matrix

In [ ]:
matrix[1] # akses baris index 1

- akses menggunakan slice

In [ ]:
matrix[1:] # akses baris index 1 & 2

In [ ]:
matrix[0:2] # akses baris index 0 & 1

- mengakses kolom dalam matrix 2D

In [ ]:
myList = [[1, 2, 3], [4, 5, 6]]

myList[0]

In [ ]:
matrix[:, -1] # akses kolom index -1

In [ ]:
matrix[:, 1] # akses kolom index 1

In [ ]:
matrix[:, 2:] # akses kolom index 2 & 3 

- Matrix 3D (baris, kolom, kedalaman)

In [61]:
matrix = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                   [[7, 8, 9],
                    [10,11,12]]])

In [ ]:
matrix[0] # akses baris ke 0

In [ ]:
matrix[0, 1] # akses baris ke 0, kolom ke 1

In [ ]:
matrix[1, 1, 1:] # akses baris ke 1, kolom ke 1, kedalaman ke 1 & 2

### Describe Vector

In [87]:
matrix = np.array([[ 1,  2,  3,  5,  5],
                   [ 4,  5,  6,  6,  6],
                   [ 7,  8,  9,  9, 10]])

In [ ]:
matrix.shape # baris, kolom

In [ ]:
matrix.shape[0]

In [ ]:
matrix.shape[1]

### Builtin Function

In [ ]:
matrix

In [ ]:
np.max(matrix)

In [ ]:
np.min(matrix)

In [ ]:
np.argmax(matrix, axis=1) # 1 : kolom, 0 : baris

In [ ]:
np.argmin(matrix, axis=0) # 1 : kolom, 0 : baris

### Reshape Matrix

In [123]:
matrix = np.array([[1,2,3,5],
                   [4,5,6,6],
                   [7,8,9,9]])

print(matrix)

[[1 2 3 5]
 [4 5 6 6]
 [7 8 9 9]]


In [ ]:
matrix.shape

In [ ]:
np.reshape(matrix, (4,3))

In [ ]:
np.reshape(matrix, (3,2,2))

### Matrix Operation

In [136]:
A = np.array([[1, 3, 1],
              [5, 2, 1]])

B = np.array([[0, 0, 1],
              [3, 5, 1]])

#### Penjumlahan Matrix

![](resource/penjumlahan_matrix.PNG)

In [ ]:
A + B

In [ ]:
A - B